# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# 本文件保留 GEM12 Max 的硬件探测结果；下方数据盘、bind mount 和 swap 为本机布局。
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f3c0e2e7-f55c-4dd4-ac8e-4738e8ac7644";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/11E0-7CA3";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # 数据盘独立挂载，用户目录和服务私有数据通过 bind mount 放到这里。
  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/cb3d302e-5a9e-41f2-acbd-8f6977c6a69c";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd:3"
      "ssd"
      "discard=async"
      "space_cache=v2"
    ];
  };

  # 用户家目录绑定到数据盘，便于系统盘重装时保留个人数据。
  fileSystems."/home/hualimao" = {
    device = "/data/home/hualimao";
    fsType = "none";
    options = [ "bind" ];
    depends = [ "/data" ];
  };

  # systemd DynamicUser 服务的私有状态目录同样落在数据盘。
  fileSystems."/var/lib/private" = {
    device = "/data/var/lib/private";
    fsType = "none";
    options = [ "bind" ];
    depends = [ "/data" ];
  };

  # 服务密钥必须位于 Nix Store 外，这里统一绑定到数据盘。
  fileSystems."/var/lib/secrets" = {
    device = "/data/var/lib/secrets";
    fsType = "none";
    options = [ "bind" ];
    depends = [ "/data" ];
  };

  # 使用 swapfile 保留内存压力下的兜底空间。
  swapDevices = [
    {
      device = "/swapfile";
      size = 32 * 1024;
    }
  ];

  # 自动探测的硬件平台与 AMD 微码开关。
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
